"""wgpu runner for Gemma 3: full decoder forward pass on the GPU.

Every shader executed here is generated by py_shader_lang_wgpu from the
Python kernels in gemma3/kernels.py. The CPU only orchestrates dispatches,
updates small parameter buffers, and does the final argmax.
"""

from __future__ import annotations

import re
import time
from collections import defaultdict

import numpy as np
import wgpu

from . import kernels as K
from .loader import GemmaConfig

_MAX_QUERIES = 2048  # timestamps per step (2 per dispatch); we use ~800


def _binding_access(wgsl: str) -> list[bool]:
    """Per binding index: True if read_write, from the generated WGSL."""
    out = {}
    for m in re.finditer(r"@binding\((\d+)\) var<storage, (read_write|read)>", wgsl):
        out[int(m.group(1))] = m.group(2) == "read_write"
    return [out[i] for i in sorted(out)]


class GemmaGPU:
    #: weight tensors stored as f16 on GPU when dtype="f16"
    _F16_WEIGHTS = ("qkv_proj", "o_proj", "gateup_proj", "down_proj",
                    "embed_tokens")

    def __init__(self, config: GemmaConfig, weights: dict[str, np.ndarray],
                 max_seq: int = 1024, profile: bool = False,
                 dtype: str = "f16") -> None:
        self.cfg = config
        self.max_seq = max_seq
        self.profile = profile

        adapter = wgpu.gpu.request_adapter_sync(power_preference="high-performance")
        if dtype == "f16" and "shader-f16" not in adapter.features:
            dtype = "f32"  # graceful fallback
        self.dtype = dtype
        embed_bytes = config.vocab_size * config.hidden_size * 4
        limits = {
            "max-buffer-size": max(embed_bytes, 1 << 28),
            "max-storage-buffer-binding-size": max(embed_bytes, 1 << 28),
        }
        features = []
        self._sg_feature = "subgroup" in adapter.features
        if self._sg_feature:
            features.append("subgroup")
        if dtype == "f16":
            features.append("shader-f16")
        if profile:
            if "timestamp-query" not in adapter.features:
                raise RuntimeError("profile=True requires the timestamp-query feature")
            features.append("timestamp-query")
        self.device = adapter.request_device_sync(
            required_limits=limits, required_features=features)
        q = self.device.queue

        if profile:
            self._qs = self.device.create_query_set(
                type=wgpu.QueryType.timestamp, count=_MAX_QUERIES)
            self._q_resolve = self.device.create_buffer(
                size=_MAX_QUERIES * 8,
                usage=wgpu.BufferUsage.QUERY_RESOLVE | wgpu.BufferUsage.COPY_SRC)
            # label -> [count, total_ns, threads]
            self._prof_kernels: dict[str, list] = defaultdict(lambda: [0, 0, 0])
        # CPU-side phase timers are cheap: always collected
        self._prof_phases: dict[str, float] = defaultdict(float)
        # (kv_len, wall_seconds, want_logits) per step
        self._prof_steps: list[tuple[int, float, bool]] = []

        # --- pipelines (one per kernel) ---
        self._pipelines: dict[str, tuple] = {}
        for name, kern in K.KERNELS.items():
            if name.endswith("_f16") and self.dtype != "f16":
                continue  # f16 shaders need the shader-f16 feature
            if name.endswith("_sg") and not self._sg_feature:
                continue  # subgroup shaders need the subgroup feature
            module = self._shader_module(kern.wgsl)
            access = _binding_access(kern.wgsl)
            entries = [
                {
                    "binding": i,
                    "visibility": wgpu.ShaderStage.COMPUTE,
                    "buffer": {
                        "type": wgpu.BufferBindingType.storage if rw
                        else wgpu.BufferBindingType.read_only_storage
                    },
                }
                for i, rw in enumerate(access)
            ]
            layout = self.device.create_bind_group_layout(entries=entries)
            pipeline = self.device.create_compute_pipeline(
                layout=self.device.create_pipeline_layout(bind_group_layouts=[layout]),
                compute={"module": module, "entry_point": name},
            )
            self._pipelines[name] = (pipeline, layout)

        # Subgroup kernels assume subgroup_size >= 32; verify on this device.
        self.use_subgroups = False
        if self._sg_feature:
            self.use_subgroups = self._probe_subgroup_size() >= 32

        # resolved kernel names per call-site family
        sg = "_sg" if self.use_subgroups else ""
        f16 = self.dtype == "f16"
        self._kn = {
            "embed_scale": "embed_scale_f16" if f16 else "embed_scale",
            "matvec": "matvec_packed" if f16 else "matvec",
            "matvec_wg": ("matvec_wg_packed" + sg) if f16 else "matvec_wg",
            "rmsnorm_wg": "rmsnorm_wg" + sg,
            "rmsnorm_add_wg": "rmsnorm_add_wg" + sg,
            "attention_fused": "attention_fused" + sg,
        }

        # --- weight buffers ---
        st = wgpu.BufferUsage.STORAGE

        # Fuse QKV and gate/up projections into single matrices: one matvec
        # dispatch instead of three (two), consumed via bind-group offsets.
        merged: dict[str, np.ndarray] = {}
        skip: set[str] = set()
        for L in range(config.num_layers):
            a = f"model.layers.{L}.self_attn."
            m = f"model.layers.{L}.mlp."
            merged[a + "qkv_proj.weight"] = np.concatenate(
                [weights[a + "q_proj.weight"], weights[a + "k_proj.weight"],
                 weights[a + "v_proj.weight"]])
            merged[m + "gateup_proj.weight"] = np.concatenate(
                [weights[m + "gate_proj.weight"], weights[m + "up_proj.weight"]])
            skip |= {a + "q_proj.weight", a + "k_proj.weight", a + "v_proj.weight",
                     m + "gate_proj.weight", m + "up_proj.weight"}

        def _wdata(name: str, arr: np.ndarray) -> bytes:
            if self.dtype == "f16" and any(t in name for t in self._F16_WEIGHTS):
                return arr.astype(np.float16).tobytes()
            return arr.tobytes()

        self._wbuf = {
            name: self.device.create_buffer_with_data(data=_wdata(name, arr), usage=st)
            for name, arr in {**weights, **merged}.items()
            if name not in skip
        }

        # --- scratch buffers ---
        cfg = config
        h, hd, nh, inter = cfg.hidden_size, cfg.head_dim, cfg.num_heads, cfg.intermediate_size
        q_dim = nh * hd
        rw = wgpu.BufferUsage.STORAGE | wgpu.BufferUsage.COPY_SRC

        def fbuf(n):
            return self.device.create_buffer(size=n * 4, usage=rw)

        self.b = {
            "x": fbuf(h), "xn": fbuf(h), "norm_tmp": fbuf(h),
            "qkv": fbuf(q_dim + 2 * hd), "qn": fbuf(q_dim), "kn": fbuf(hd),
            "scores": fbuf(nh * max_seq), "attn": fbuf(q_dim), "attn_proj": fbuf(h),
            "gateup": fbuf(2 * inter), "ffh": fbuf(inter),
            "mlp_out": fbuf(h),
            "logits": fbuf(cfg.vocab_size),
        }
        upd = wgpu.BufferUsage.STORAGE | wgpu.BufferUsage.COPY_DST
        self.b["token"] = self.device.create_buffer(size=4, usage=upd)
        self.k_cache = [fbuf(max_seq * hd) for _ in range(cfg.num_layers)]
        self.v_cache = [fbuf(max_seq * hd) for _ in range(cfg.num_layers)]

        # --- dims buffers ---
        def ubuf(*vals):
            return self.device.create_buffer_with_data(
                data=np.array(vals, dtype=np.uint32).tobytes(), usage=st)

        def dynbuf(n, dtype=np.uint32):
            return self.device.create_buffer(size=n * 4, usage=upd)

        self.d = {
            "embed": ubuf(h),
            "norm_h": ubuf(1, h),
            "norm_q": ubuf(nh, hd),
            "norm_k": ubuf(1, hd),
            "mv_qkv": ubuf(q_dim + 2 * hd, h),
            "mv_o": ubuf(h, q_dim),
            "mv_gateup": ubuf(2 * inter, h),
            "mv_down": ubuf(h, inter),
            "mv_logits": ubuf(cfg.vocab_size, h),
            "rope_q": ubuf(nh, hd),
            "rope_k": ubuf(1, hd),
            "geglu": ubuf(inter),
            "add": ubuf(h),
            # dynamic (rewritten each step)
            "kv_append": dynbuf(2),
            "scores_sliding": dynbuf(5),
            "scores_full": dynbuf(5),
            "softmax": dynbuf(3),
            "attn_out": dynbuf(4),
            "rope_local": dynbuf(2, np.float32),
            "rope_global": dynbuf(2, np.float32),
        }

        # --- GPU-resident decode state ---
        N_ARGMAX_WGS = 128
        self.b["pos"] = self.device.create_buffer(size=4, usage=upd)
        self.b["out_tokens"] = self.device.create_buffer(
            size=max_seq * 4, usage=rw | wgpu.BufferUsage.COPY_DST)
        self.b["counter"] = self.device.create_buffer(
            size=4, usage=rw | wgpu.BufferUsage.COPY_DST)
        self.b["part_val"] = fbuf(N_ARGMAX_WGS)
        self.b["part_idx"] = fbuf(N_ARGMAX_WGS)
        self.d["argmax1"] = ubuf(cfg.vocab_size, N_ARGMAX_WGS)
        self.d["argmax2"] = ubuf(N_ARGMAX_WGS)
        self.d["setup_cfg"] = ubuf(cfg.sliding_window)
        self._n_argmax_wgs = N_ARGMAX_WGS

        # --- bind groups ---
        self._bg_cache: dict[tuple, object] = {}
        self._build_bind_groups(weights)

    # ------------------------------------------------------------------ #

    def _shader_module(self, code: str):
        """Compat shim: current naga rejects `enable subgroups;` while
        supporting the ops themselves — retry without the directive."""
        try:
            return self.device.create_shader_module(code=code)
        except Exception:
            if "enable subgroups;" in code:
                return self.device.create_shader_module(
                    code=code.replace("enable subgroups;", ""))
            raise

    def _probe_subgroup_size(self) -> int:
        buf = self.device.create_buffer(
            size=4, usage=wgpu.BufferUsage.STORAGE | wgpu.BufferUsage.COPY_SRC)
        pipeline, layout = self._pipelines["probe_sg"]
        bg = self.device.create_bind_group(
            layout=layout,
            entries=[{"binding": 0, "resource": {"buffer": buf, "offset": 0, "size": 4}}])
        enc = self.device.create_command_encoder()
        cp = enc.begin_compute_pass()
        cp.set_pipeline(pipeline)
        cp.set_bind_group(0, bg)
        cp.dispatch_workgroups(1, 1, 1)
        cp.end()
        self.device.queue.submit([enc.finish()])
        return int(np.frombuffer(self.device.queue.read_buffer(buf), dtype=np.uint32)[0])

    def _bg(self, kern_name: str, *buffers):
        """buffers: GPUBuffer or (GPUBuffer, offset_bytes, size_bytes) tuples."""
        def norm(b):
            return b if isinstance(b, tuple) else (b, 0, b.size)

        views = [norm(b) for b in buffers]
        key = (kern_name, *((id(b), o, sz) for b, o, sz in views))
        if key not in self._bg_cache:
            _, layout = self._pipelines[kern_name]
            self._bg_cache[key] = self.device.create_bind_group(
                layout=layout,
                entries=[
                    {"binding": i, "resource": {"buffer": b, "offset": o, "size": sz}}
                    for i, (b, o, sz) in enumerate(views)
                ],
            )
        return self._bg_cache[key]

    def _build_bind_groups(self, weights) -> None:
        cfg, b, d, w = self.cfg, self.b, self.d, self._wbuf
        emb = w["model.embed_tokens.weight"]
        self.bg_embed = self._bg(self._kn["embed_scale"], b["token"], emb, b["x"], d["embed"])
        self.bg_softmax = self._bg("attn_softmax", b["scores"], d["softmax"])

        self.bg_final_norm = self._bg(
            "rmsnorm_wg", b["x"], w["model.norm.weight"], b["xn"], d["norm_h"])
        self.bg_logits = self._bg(self._kn["matvec"], emb, b["xn"], b["logits"], d["mv_logits"])

        self.bg_setup = self._bg(
            "step_setup", b["pos"], d["kv_append"], d["scores_sliding"],
            d["scores_full"], d["rope_local"], d["rope_global"], d["setup_cfg"])
        self.bg_argmax1 = self._bg(
            "argmax_stage1", b["logits"], b["part_val"], b["part_idx"], d["argmax1"])
        self.bg_argmax2 = self._bg(
            "argmax_stage2", b["part_val"], b["part_idx"], b["token"],
            b["out_tokens"], b["counter"], d["argmax2"])

        self.layer_bgs = []
        hd, nh = cfg.head_dim, cfg.num_heads
        h, inter = cfg.hidden_size, cfg.intermediate_size
        q_bytes = nh * hd * 4          # q slice of the qkv buffer
        kv_bytes = hd * 4              # k / v slices
        for L in range(cfg.num_layers):
            p = f"model.layers.{L}."
            sliding = cfg.layer_types[L] == "sliding_attention"
            rope_f = d["rope_local"] if sliding else d["rope_global"]
            scores_d = d["scores_sliding"] if sliding else d["scores_full"]
            qkv = b["qkv"]
            gu = b["gateup"]
            self.layer_bgs.append({
                "norm1": self._bg(self._kn["rmsnorm_wg"], b["x"], w[p + "input_layernorm.weight"],
                                  b["xn"], d["norm_h"]),
                "mv_qkv": self._bg(self._kn["matvec_wg"],
                                   w[p + "self_attn.qkv_proj.weight"],
                                   b["xn"], qkv, d["mv_qkv"]),
                "qnorm": self._bg(self._kn["rmsnorm_wg"], (qkv, 0, q_bytes),
                                  w[p + "self_attn.q_norm.weight"],
                                  b["qn"], d["norm_q"]),
                "knorm": self._bg(self._kn["rmsnorm_wg"], (qkv, q_bytes, kv_bytes),
                                  w[p + "self_attn.k_norm.weight"],
                                  b["kn"], d["norm_k"]),
                "rope_q": self._bg("rope", b["qn"], rope_f, d["rope_q"]),
                "rope_k": self._bg("rope", b["kn"], rope_f, d["rope_k"]),
                "app_k": self._bg("kv_append", b["kn"], self.k_cache[L], d["kv_append"]),
                "app_v": self._bg("kv_append", (qkv, q_bytes + kv_bytes, kv_bytes),
                                  self.v_cache[L], d["kv_append"]),
                "attn": self._bg(self._kn["attention_fused"], b["qn"], self.k_cache[L],
                                 self.v_cache[L], b["scores"], b["attn"], scores_d),
                "mv_o": self._bg(self._kn["matvec_wg"], w[p + "self_attn.o_proj.weight"],
                                 b["attn"], b["attn_proj"], d["mv_o"]),
                "norm_pa_add": self._bg(self._kn["rmsnorm_add_wg"], b["attn_proj"],
                                        w[p + "post_attention_layernorm.weight"],
                                        b["x"], d["norm_h"]),
                "norm_pf": self._bg(self._kn["rmsnorm_wg"], b["x"],
                                    w[p + "pre_feedforward_layernorm.weight"],
                                    b["xn"], d["norm_h"]),
                "mv_gateup": self._bg(self._kn["matvec_wg"],
                                      w[p + "mlp.gateup_proj.weight"],
                                      b["xn"], gu, d["mv_gateup"]),
                "geglu": self._bg("geglu", (gu, 0, inter * 4), (gu, inter * 4, inter * 4),
                                  b["ffh"], d["geglu"]),
                "mv_down": self._bg(self._kn["matvec_wg"], w[p + "mlp.down_proj.weight"],
                                    b["ffh"], b["mlp_out"], d["mv_down"]),
                "norm_pff_add": self._bg(self._kn["rmsnorm_add_wg"], b["mlp_out"],
                                         w[p + "post_feedforward_layernorm.weight"],
                                         b["x"], d["norm_h"]),
            })

    # ------------------------------------------------------------------ #

    def _write_step_params(self, token_id: int, pos: int) -> None:
        cfg, q = self.cfg, self.device.queue
        kv_len = pos + 1
        start = max(0, kv_len - cfg.sliding_window)
        nh, hd, ms = cfg.num_heads, cfg.head_dim, self.max_seq

        def u32(buf, *vals):
            q.write_buffer(buf, 0, np.array(vals, dtype=np.uint32).tobytes())

        u32(self.b["token"], token_id)
        u32(self.d["kv_append"], hd, pos)
        u32(self.d["scores_sliding"], nh, hd, kv_len, start, ms)
        u32(self.d["scores_full"], nh, hd, kv_len, 0, ms)
        u32(self.d["softmax"], nh, kv_len, ms)
        u32(self.d["attn_out"], nh, hd, kv_len, ms)
        q.write_buffer(self.d["rope_local"], 0,
                       np.array([cfg.rope_theta_local, pos], dtype=np.float32).tobytes())
        q.write_buffer(self.d["rope_global"], 0,
                       np.array([cfg.rope_theta_global, pos], dtype=np.float32).tobytes())

    def _encode_forward(self, run, want_logits: bool) -> None:
        """Encode one full decoder forward pass via the given run() callback."""
        cfg = self.cfg
        nh, hd, h = cfg.num_heads, cfg.head_dim, cfg.hidden_size
        run(self._kn["embed_scale"], self.bg_embed, h, label="embed")
        inter = cfg.intermediate_size
        for L in range(cfg.num_layers):
            bg = self.layer_bgs[L]
            run(self._kn["rmsnorm_wg"], bg["norm1"], h, label="norm_input", grid=(1, 1, 1))
            run(self._kn["matvec_wg"], bg["mv_qkv"], nh * hd + 2 * hd,
                label="mv_qkv", grid=(nh * hd + 2 * hd, 1, 1))
            run(self._kn["rmsnorm_wg"], bg["qnorm"], nh * hd, label="qk_norm", grid=(nh, 1, 1))
            run(self._kn["rmsnorm_wg"], bg["knorm"], hd, label="qk_norm", grid=(1, 1, 1))
            run("rope", bg["rope_q"], nh * hd // 2, label="rope")
            run("rope", bg["rope_k"], hd // 2, label="rope")
            run("kv_append", bg["app_k"], hd, label="kv_append")
            run("kv_append", bg["app_v"], hd, label="kv_append")
            run(self._kn["attention_fused"], bg["attn"], nh * 64, label="attn_fused",
                grid=(nh, 1, 1))
            run(self._kn["matvec_wg"], bg["mv_o"], h, label="mv_o", grid=(h, 1, 1))
            run(self._kn["rmsnorm_add_wg"], bg["norm_pa_add"], h, label="norm_post_add",
                grid=(1, 1, 1))
            run(self._kn["rmsnorm_wg"], bg["norm_pf"], h, label="norm_pre_ff", grid=(1, 1, 1))
            run(self._kn["matvec_wg"], bg["mv_gateup"], 2 * inter,
                label="mv_gateup", grid=(2 * inter, 1, 1))
            run("geglu", bg["geglu"], inter, label="geglu")
            run(self._kn["matvec_wg"], bg["mv_down"], h, label="mv_down",
                grid=(h, 1, 1))
            run(self._kn["rmsnorm_add_wg"], bg["norm_pff_add"], h, label="norm_post_add",
                grid=(1, 1, 1))

        if want_logits:
            run(self._kn["rmsnorm_wg"], self.bg_final_norm, h, label="norm_final", grid=(1, 1, 1))
            run(self._kn["matvec"], self.bg_logits, cfg.vocab_size, label="mv_logits")

    def step(self, token_id: int, pos: int, want_logits: bool = True) -> np.ndarray | None:
        """Run one decoder forward pass on the GPU for `token_id` at `pos`."""
        if pos >= self.max_seq:
            raise ValueError(f"position {pos} exceeds max_seq {self.max_seq}")
        cfg = self.cfg
        nh, hd, h = cfg.num_heads, cfg.head_dim, cfg.hidden_size
        kv_len = pos + 1
        t_step = time.perf_counter()
        self._write_step_params(token_id, pos)
        t0 = time.perf_counter()

        enc = self.device.create_command_encoder()
        cp = None if self.profile else enc.begin_compute_pass()
        pass_labels: list[tuple[str, int]] = []  # (label, n_threads)

        def run(name, bg, n_threads, wg=64, label=None, grid=None):
            nonlocal cp
            pipeline, _ = self._pipelines[name]
            if self.profile:
                i = len(pass_labels) * 2
                cp = enc.begin_compute_pass(timestamp_writes={
                    "query_set": self._qs,
                    "beginning_of_pass_write_index": i,
                    "end_of_pass_write_index": i + 1,
                })
                pass_labels.append((label or name, n_threads))
            cp.set_pipeline(pipeline)
            cp.set_bind_group(0, bg)
            if grid is not None:
                cp.dispatch_workgroups(*grid)
            else:
                cp.dispatch_workgroups((n_threads + wg - 1) // wg, 1, 1)
            if self.profile:
                cp.end()

        self._encode_forward(run, want_logits)

        if self.profile:
            enc.resolve_query_set(self._qs, 0, len(pass_labels) * 2,
                                  self._q_resolve, 0)
        else:
            cp.end()
        t1 = time.perf_counter()
        self.device.queue.submit([enc.finish()])
        t2 = time.perf_counter()

        logits = None
        if want_logits:
            raw = self.device.queue.read_buffer(self.b["logits"])
            logits = np.frombuffer(raw, dtype=np.float32).copy()
        t3 = time.perf_counter()

        if self.profile:
            raw = self.device.queue.read_buffer(self._q_resolve)
            ts = np.frombuffer(raw, dtype=np.uint64)[: len(pass_labels) * 2]
            for j, (label, n_threads) in enumerate(pass_labels):
                dur = int(ts[2 * j + 1] - ts[2 * j])
                rec = self._prof_kernels[label]
                rec[0] += 1
                rec[1] += dur
                rec[2] = n_threads
        t4 = time.perf_counter()
        ph = self._prof_phases
        ph["params_write"] += t0 - t_step
        ph["encode"] += t1 - t0
        ph["submit"] += t2 - t1
        ph["logits_readback"] += t3 - t2
        if self.profile:
            ph["ts_readback (profiling overhead)"] += t4 - t3
        self._prof_steps.append((kv_len, t4 - t_step, want_logits))
        return logits

    def read_hidden(self) -> np.ndarray:
        """Read back the current hidden state x (for verification)."""
        raw = self.device.queue.read_buffer(self.b["x"])
        return np.frombuffer(raw, dtype=np.float32).copy()

    # ------------------------------------------------------------------ #
    # Profiling                                                            #
    # ------------------------------------------------------------------ #

    def _bytes_per_call(self, label: str, kv_mean: float) -> float | None:
        """Approximate memory traffic per dispatch (bytes), for GB/s."""
        cfg = self.cfg
        h, hd, nh, inter, v = (cfg.hidden_size, cfg.head_dim, cfg.num_heads,
                               cfg.intermediate_size, cfg.vocab_size)
        q_dim = nh * hd
        wb = 2.0 if self.dtype == "f16" else 4.0
        mv = lambda n_out, n_in: wb * n_out * n_in + 4.0 * (n_in + n_out)
        table = {
            "mv_qkv": mv(q_dim + 2 * hd, h),
            "mv_o": mv(h, q_dim),
            "mv_gateup": mv(2 * inter, h),
            "mv_down": mv(h, inter),
            "mv_logits": mv(v, h),
            "attn_fused": 4.0 * (q_dim + 2 * kv_mean * hd + 2 * nh * kv_mean),
        }
        return table.get(label)

    def profile_report(self) -> str:
        """Human-readable profiling summary (requires profile=True)."""
        if not self.profile:
            raise RuntimeError("construct with profile=True to collect timings")
        if not self._prof_steps:
            return "no steps profiled"

        kv_mean = float(np.mean([s[0] for s in self._prof_steps]))
        total_ns = sum(rec[1] for rec in self._prof_kernels.values())
        lines = []
        lines.append(f"== GPU time by call-site ({len(self._prof_steps)} steps, "
                     f"mean kv_len {kv_mean:.0f}) ==")
        lines.append(f"{'call-site':<14}{'count':>7}{'mean µs':>9}"
                     f"{'total ms':>10}{'share':>7}{'threads':>9}{'~GB/s':>7}")
        rows = sorted(self._prof_kernels.items(), key=lambda kv: -kv[1][1])
        for label, (count, ns, threads) in rows:
            mean_us = ns / count / 1e3
            share = 100.0 * ns / total_ns if total_ns else 0.0
            nbytes = self._bytes_per_call(label, kv_mean)
            gbs = f"{nbytes * count / ns:.1f}" if nbytes and ns else "-"
            lines.append(f"{label:<14}{count:>7}{mean_us:>9.1f}"
                         f"{ns / 1e6:>10.2f}{share:>6.1f}%{threads:>9}{gbs:>7}")

        wall = sum(s[1] for s in self._prof_steps)
        lines.append("")
        lines.append(f"GPU busy: {total_ns / 1e6:.1f} ms | step wall: {wall * 1e3:.1f} ms "
                     f"| GPU utilization: {total_ns / 1e9 / wall * 100:.0f}%")

        lines.append("")
        lines.append("== CPU phases (totals) ==")
        for phase, sec in sorted(self._prof_phases.items(), key=lambda kv: -kv[1]):
            lines.append(f"  {phase:<32}{sec * 1e3:>9.1f} ms")

        decode = [(k, w) for k, w, wl in self._prof_steps if wl]
        prefill = [(k, w) for k, w, wl in self._prof_steps if not wl]
        lines.append("")
        lines.append("== steps ==")
        if prefill:
            lines.append(f"  prefill: {len(prefill)} steps, "
                         f"mean {np.mean([w for _, w in prefill]) * 1e3:.2f} ms")
        if decode:
            lines.append(f"  decode:  {len(decode)} steps, "
                         f"mean {np.mean([w for _, w in decode]) * 1e3:.2f} ms")
            if len(decode) >= 8:
                qn = len(decode) // 4
                first = np.mean([w for _, w in decode[:qn]]) * 1e3
                last = np.mean([w for _, w in decode[-qn:]]) * 1e3
                k0 = np.mean([k for k, _ in decode[:qn]])
                k1 = np.mean([k for k, _ in decode[-qn:]])
                lines.append(f"  decode latency vs kv_len: {first:.2f} ms @ kv≈{k0:.0f} "
                             f"→ {last:.2f} ms @ kv≈{k1:.0f}")

        # bandwidth floor: every decode step reads all weights once
        wbytes = sum(b.size for b in self._wbuf.values())
        lines.append("")
        lines.append(f"weights: {wbytes / 1e9:.2f} GB f32 → at ~200 GB/s the "
                     f"bandwidth floor is ≈{wbytes / 200e9 * 1e3:.1f} ms/token "
                     f"({200e9 / wbytes:.0f} tok/s ceiling)")
        return "\n".join(lines)

    @staticmethod
    def _pick(logits: np.ndarray, temperature: float, top_k: int,
              rng: np.random.Generator) -> int:
        if temperature <= 0.0:
            return int(np.argmax(logits))
        scaled = logits.astype(np.float64) / temperature
        if top_k > 0:
            kth = np.partition(scaled, -top_k)[-top_k]
            scaled = np.where(scaled < kth, -np.inf, scaled)
        scaled -= scaled.max()
        probs = np.exp(scaled)
        probs /= probs.sum()
        return int(rng.choice(len(probs), p=probs))

    def _generate_resident(self, prompt_ids: list[int], max_new_tokens: int,
                           on_token, chunk: int = 16) -> list[int]:
        """Greedy decode fully on-GPU: token feedback, params, and argmax
        never leave the device; the CPU checks for EOS once per chunk."""
        q = self.device.queue
        # prefill all but the last prompt token (no logits needed)
        for pos, tid in enumerate(prompt_ids[:-1]):
            self.step(tid, pos, want_logits=False)

        # seed resident state: the last prompt token produces generation[0]
        start_pos = len(prompt_ids) - 1
        q.write_buffer(self.b["token"],
                       0, np.array([prompt_ids[-1]], dtype=np.uint32).tobytes())
        q.write_buffer(self.b["pos"],
                       0, np.array([start_pos], dtype=np.uint32).tobytes())
        q.write_buffer(self.b["counter"], 0, np.zeros(1, dtype=np.uint32).tobytes())

        cfg = self.cfg
        emitted = 0
        out: list[int] = []
        produced = 0
        budget = min(max_new_tokens, self.max_seq - start_pos)
        while produced < budget:
            k = min(chunk, budget - produced)
            t0 = time.perf_counter()
            enc = self.device.create_command_encoder()
            cp = enc.begin_compute_pass()

            def run(name, bg, n_threads, wg=64, label=None, grid=None):
                pipeline, _ = self._pipelines[name]
                cp.set_pipeline(pipeline)
                cp.set_bind_group(0, bg)
                if grid is not None:
                    cp.dispatch_workgroups(*grid)
                else:
                    cp.dispatch_workgroups((n_threads + wg - 1) // wg, 1, 1)

            for _ in range(k):
                run("step_setup", self.bg_setup, 1, grid=(1, 1, 1))
                self._encode_forward(run, want_logits=True)
                run("argmax_stage1", self.bg_argmax1, self._n_argmax_wgs * 64,
                    grid=(self._n_argmax_wgs, 1, 1))
                run("argmax_stage2", self.bg_argmax2, 64, grid=(1, 1, 1))
            cp.end()
            t1 = time.perf_counter()
            q.submit([enc.finish()])
            produced += k

            raw = q.read_buffer(self.b["out_tokens"], size=produced * 4)
            toks = np.frombuffer(raw, dtype=np.uint32)
            t2 = time.perf_counter()
            ph = self._prof_phases
            ph["encode"] += t1 - t0
            ph["chunk_submit_readback"] += t2 - t1
            self._prof_steps.append((start_pos + produced, (t2 - t0) / k, True))

            stop = False
            for tid in toks[emitted:]:
                tid = int(tid)
                out.append(tid)
                if on_token is not None:
                    on_token(tid)
                emitted += 1
                if tid in cfg.eos_token_ids:
                    stop = True
                    break
            if stop:
                break
        return out

    def generate(self, prompt_ids: list[int], max_new_tokens: int = 64,
                 on_token=None, temperature: float = 0.0, top_k: int = 64,
                 seed: int | None = None) -> list[int]:
        """Generate token ids (without prompt). temperature<=0 → greedy."""
        if temperature <= 0.0 and not self.profile:
            # greedy: fully GPU-resident decode (per-kernel profiling needs
            # the per-step path, so profile mode falls through)
            return self._generate_resident(prompt_ids, max_new_tokens, on_token)

        rng = np.random.default_rng(seed)
        logits = None
        for pos, tid in enumerate(prompt_ids):
            last = pos == len(prompt_ids) - 1
            logits = self.step(tid, pos, want_logits=last)

        out: list[int] = []
        pos = len(prompt_ids)
        for _ in range(max_new_tokens):
            next_id = self._pick(logits, temperature, top_k, rng)
            out.append(next_id)
            if on_token is not None:
                on_token(next_id)
            if next_id in self.cfg.eos_token_ids:
                break
            if pos >= self.max_seq:
                break  # KV cache full — stop cleanly
            logits = self.step(next_id, pos)
            pos += 1
        return out
